[package]
name = "genesis-render"
version.workspace = true
edition.workspace = true
description = "WGPU-based renderer - meshes, shadows, PBR, particles, water, post-processing"
[dependencies]
wgpu = { workspace = true }
winit = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
bytemuck = { workspace = true }
async-trait.workspace = true
tokio = { workspace = true }
genesis-core = { workspace = true }
genesis-math = { workspace = true }
genesis-ecs  = { workspace = true }
