//! Advanced Node-Based Material Editor for Genesis Engine
use serde::{Serialize, Deserialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ShaderNode {
    TextureSample { path: String },
    ColorConstant { r: f32, g: f32, b: f32, a: f32 },
    Math { op: String },
    NormalMap,
    Fresnel,
    PbrOutput {
        albedo: [f32; 4],
        metallic: f32,
        roughness: f32,
        ao: f32,
        emissive: [f32; 3],
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialGraph {
    pub nodes: Vec<ShaderNode>,
    pub connections: Vec<(usize, usize)>, // (from_node, to_node)
}

impl MaterialGraph {
    pub fn compile_to_wgsl(&self) -> String {
        // Mock compilation to WGSL for genesis-render
        "// Generated by Genesis Material Editor\nfn main() { ... }".to_string()
    }
}
