//! Genesis Material System
//!
//! Complete PBR material system covering every rendering use case:
//!
//! MATERIAL TYPES:
//! - Standard PBR (Metallic-Roughness workflow)
//! - Specular-Glossiness PBR (legacy workflow)
//! - Unlit (UI, skybox, emissive only)
//! - Toon / Cel-Shaded
//! - Hair (Kajiya-Kay + dual scattering)
//! - Skin (Sub-Surface Scattering)
//! - Eyes (cornea refraction, iris parallax)
//! - Fabric / Cloth (cotton, silk, velvet, leather)
//! - Liquid (water, slime, blood, lava)
//! - Glass / Refraction
//! - Foliage (two-sided, translucency)
//! - Terrain (multi-layer blend)
//! - Decal (projected onto other surfaces)
//! - Post-Process (screen-space effects)
//!
//! TEXTURE MAPS:
//! - Albedo / Base Color (RGB + Alpha)
//! - Normal Map (tangent-space DirectX or OpenGL)
//! - Roughness (R channel)
//! - Metallic (G channel)
//! - Ambient Occlusion (B channel)
//! - Emissive (RGB)
//! - Height / Displacement (parallax occlusion)
//! - Opacity (A or separate)
//! - Transmission (for glass/cloth)
//! - Subsurface Color + Radius
//! - Anisotropy (brushed metal, hair)
//! - Clearcoat (car paint, lacquer)
//! - Sheen (fabric)
//! - Iridescence (soap bubble, thin film)
//!
//! PROCEDURAL TEXTURES:
//! - Noise (Perlin, Simplex, Voronoi, FBM)
//! - Checker, Brick, Gradient, Wave
//! - Rust, Grunge, Scratches, Dirt layers
//! - Weather damage (rain streaks, moss, cracks)

use serde::{Serialize, Deserialize};
use std::collections::HashMap;
use genesis_math::color::Color;

// ─── Texture Reference ────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TextureRef {
    /// Loaded from asset file
    Asset { asset_id: String },
    /// Solid color (no texture needed)
    Color([f32; 4]),
    /// Single float value
    Value(f32),
    /// Procedural texture
    Procedural(ProceduralTexture),
    /// Generated by AI
    AiGenerated { prompt: String, resolution: u32, asset_id: Option<String> },
    /// None (use default)
    None,
}

impl TextureRef {
    pub fn is_none(&self) -> bool { matches!(self, Self::None) }
    pub fn white() -> Self { Self::Color([1.0, 1.0, 1.0, 1.0]) }
    pub fn black() -> Self { Self::Color([0.0, 0.0, 0.0, 1.0]) }
    pub fn flat_normal() -> Self { Self::Color([0.5, 0.5, 1.0, 1.0]) }
}

// ─── Procedural Textures ─────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProceduralTexture {
    pub proc_type: ProceduralType,
    pub resolution: u32,
    pub scale: f32,
    pub offset: [f32; 3],
    pub color_a: [f32; 4],
    pub color_b: [f32; 4],
    pub seed: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ProceduralType {
    PerlinNoise    { octaves: u32, persistence: f32, lacunarity: f32 },
    SimplexNoise   { octaves: u32 },
    VoronoiNoise   { randomness: f32, distance_metric: DistanceMetric },
    FractionalBrownian { octaves: u32, gain: f32 },
    Checker        { size: f32 },
    Brick          { mortar_size: f32, brick_width: f32, brick_height: f32 },
    Gradient       { direction: GradientDir },
    Wave           { wave_type: WaveType, distortion: f32 },
    Wood           { rings: u32, distortion: f32 },
    Marble         { scale: f32, distortion: f32, sharpness: f32 },
    // Surface aging / damage
    Rust           { coverage: f32, edge_only: bool },
    Grunge         { density: f32, variety: f32 },
    Scratches      { density: f32, depth: f32, random_direction: bool },
    Cracks         { density: f32, width: f32, depth: f32 },
    Moss           { coverage: f32, normal_influence: f32 },
    Dirt           { coverage: f32, layer: DirtLayer },
    WaterStains    { coverage: f32 },
    RainStreaks    { density: f32, flow_dir: [f32; 3] },
    Fingerprints   { density: f32 },
    Snow           { coverage: f32, rim_only: bool },
    Burn           { coverage: f32, char_edge: bool },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DistanceMetric { Euclidean, Manhattan, Chebyshev }
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum GradientDir { Horizontal, Vertical, Diagonal, Radial, Conical, Spherical }
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WaveType { Sine, Sawtooth, Triangle, Square }
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DirtLayer { Base, Rim, Crevice, All }

// ─── UV Settings ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UvSettings {
    pub channel: u32,        // UV channel (0, 1, 2...)
    pub scale: [f32; 2],
    pub offset: [f32; 2],
    pub rotation: f32,
    pub tiling: UvTiling,
    pub projection: UvProjection,
    pub flip_u: bool,
    pub flip_v: bool,
    pub swap_uv: bool,
}

impl Default for UvSettings {
    fn default() -> Self {
        Self {
            channel: 0, scale: [1.0, 1.0], offset: [0.0, 0.0],
            rotation: 0.0, tiling: UvTiling::Repeat,
            projection: UvProjection::Uv, flip_u: false, flip_v: false, swap_uv: false,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UvTiling { Repeat, Mirror, Clamp, Border }
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UvProjection { Uv, Planar, Triplanar, Spherical, Cylindrical, Box }

// ─── The Master Material ──────────────────────────────────────────────────────

/// The complete material definition for any surface in Genesis
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Material {
    pub id: String,
    pub name: String,
    pub material_type: MaterialType,

    // ─── PBR Core ────────────────────────────────────────────────────────────
    /// Base color / albedo (sRGB)
    pub albedo: TextureRef,
    pub albedo_tint: [f32; 4],
    /// Tangent-space normal map
    pub normal: TextureRef,
    pub normal_strength: f32,
    pub normal_map_format: NormalMapFormat,
    /// Roughness (0=mirror, 1=fully rough)
    pub roughness: TextureRef,
    pub roughness_value: f32,
    /// Metallic (0=dielectric, 1=conductor)
    pub metallic: TextureRef,
    pub metallic_value: f32,
    /// Ambient occlusion
    pub ao: TextureRef,
    pub ao_strength: f32,
    /// Emissive (self-illumination)
    pub emissive: TextureRef,
    pub emissive_color: [f32; 3],
    pub emissive_strength: f32,
    /// Height / displacement
    pub height: TextureRef,
    pub height_scale: f32,
    pub height_bias: f32,
    pub parallax_mode: ParallaxMode,

    // ─── Transparency ────────────────────────────────────────────────────────
    pub opacity: TextureRef,
    pub opacity_value: f32,
    pub blend_mode: BlendMode,
    pub alpha_cutoff: f32,
    pub alpha_dither: bool,
    pub alpha_to_coverage: bool,

    // ─── Advanced PBR ────────────────────────────────────────────────────────
    /// Transmission (glass, cloth) 0-1
    pub transmission: f32,
    pub transmission_color: [f32; 3],
    pub ior: f32,             // Index of refraction (glass=1.5, diamond=2.4)
    pub refraction_scale: f32,

    /// Sub-surface scattering (skin, wax, marble)
    pub sss_enabled: bool,
    pub sss_color: [f32; 3],
    pub sss_radius: [f32; 3], // per-channel falloff radius
    pub sss_profile: SssProfile,
    pub sss_anisotropy: f32,
    pub sss_strength: f32,

    /// Clearcoat (car paint, lacquer, varnish)
    pub clearcoat: f32,
    pub clearcoat_roughness: f32,
    pub clearcoat_normal: TextureRef,

    /// Sheen (fabric, cloth)
    pub sheen: f32,
    pub sheen_roughness: f32,
    pub sheen_color: [f32; 3],

    /// Iridescence (soap bubble, thin film, beetle wings, pearl)
    pub iridescence: f32,
    pub iridescence_ior: f32,
    pub iridescence_thickness_min: f32,
    pub iridescence_thickness_max: f32,

    /// Anisotropy (brushed metal, hair, satin)
    pub anisotropy: f32,
    pub anisotropy_rotation: f32,
    pub anisotropy_map: TextureRef,

    // ─── Special Material Params ─────────────────────────────────────────────
    pub special: SpecialMaterialParams,

    // ─── Rendering ───────────────────────────────────────────────────────────
    pub two_sided: bool,
    pub cull_mode: CullMode,
    pub depth_write: bool,
    pub depth_test: bool,
    pub depth_bias: f32,
    pub wireframe: bool,
    pub cast_shadow: bool,
    pub receive_shadow: bool,
    pub receive_decals: bool,
    pub receive_ao: bool,
    pub vertex_color_multiplier: bool,

    // ─── UV ──────────────────────────────────────────────────────────────────
    pub uv: UvSettings,
    pub uv_channel_albedo: u32,
    pub uv_channel_normal: u32,
    pub uv_channel_roughness: u32,
    pub uv_channel_ao: u32,

    // ─── Tessellation ────────────────────────────────────────────────────────
    pub tessellation: Option<TessellationSettings>,

    // ─── Wind Response ───────────────────────────────────────────────────────
    pub wind_response: Option<WindMaterialResponse>,

    // ─── Tags ────────────────────────────────────────────────────────────────
    pub tags: Vec<String>,
    pub custom_params: HashMap<String, f32>,
    pub shader_graph_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum NormalMapFormat { OpenGl, DirectX }

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ParallaxMode {
    None,
    Simple,
    POM { min_samples: u32, max_samples: u32 }, // Parallax Occlusion Mapping
    Relief { steps: u32 },
    Displacement, // actual geometry displacement (requires tessellation)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BlendMode {
    Opaque,
    AlphaTest,
    AlphaBlend,
    Additive,
    Multiply,
    Screen,
    Premultiplied,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum CullMode { Back, Front, None }

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SssProfile {
    Skin,    // Penner skin profile
    Marble,
    Wax,
    Milk,
    Plant,
    Custom { scatter_radius: f32 },
}

// ─── Material Types ───────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MaterialType {
    /// Standard physically-based material
    Standard,
    /// Toon / cel-shaded (flat colors, outlines)
    Toon { shade_steps: u32, outline_width: f32, outline_color: [f32; 4] },
    /// Hair (Kajiya-Kay dual scattering)
    Hair { primary_shift: f32, secondary_shift: f32, primary_specular: f32, secondary_specular: f32 },
    /// Human / character skin (SSS preset)
    Skin { skin_tone: [f32; 4], subsurface_weight: f32 },
    /// Eyes (cornea, iris, pupil)
    Eye { ior: f32, iris_scale: f32, pupil_size: f32, sclera_roughness: f32 },
    /// Fabric
    Fabric { fabric_type: FabricType },
    /// Water / liquid surface
    Water { wave_normal: Option<String>, foam_texture: Option<String>, depth_color: [f32; 4] },
    /// Glass / refraction
    Glass { tint: [f32; 4], frosted: bool, thickness: f32 },
    /// Foliage (two-sided, wind, translucency)
    Foliage { translucency: f32, subsurface_color: [f32; 3], wind_influence: f32 },
    /// Terrain (multi-layer blend up to 8 layers)
    Terrain { layers: Vec<TerrainMaterialLayer> },
    /// Decal (projected onto geometry)
    Decal { opacity: f32, affects_albedo: bool, affects_normal: bool, affects_roughness: bool },
    /// Particle (billboard, GPU-optimized)
    Particle { soft_particle: bool, soft_particle_fade: f32 },
    /// Hologram / energy shield
    Hologram { scan_line_density: f32, edge_glow: f32, distortion: f32 },
    /// Lava / magma
    Lava { flow_speed: f32, hot_color: [f32; 4], cool_color: [f32; 4] },
    /// Unlit (no lighting calculation)
    Unlit,
    /// Custom shader graph
    Custom { shader_graph_id: String },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FabricType {
    Cotton     { thread_visibility: f32 },
    Silk       { sheen_intensity: f32, direction: f32 },
    Velvet     { backscatter: f32 },
    Wool       { fiber_length: f32 },
    Denim      { warp_color: [f32; 4], weft_color: [f32; 4] },
    Leather    { wrinkle_map: Option<String>, sheen: f32 },
    Lace       { opacity_cutoff: f32 },
    Chainmail  { link_size: f32 },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TerrainMaterialLayer {
    pub name: String,
    pub albedo: TextureRef,
    pub normal: TextureRef,
    pub roughness: TextureRef,
    pub blend_mode: TerrainBlend,
    pub height_range: [f32; 2],
    pub slope_range: [f32; 2],
    pub tiling_scale: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TerrainBlend { HeightBlend, SlopeBlend, TextureBlend, WeightMap }

// ─── Special Material Params ─────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpecialMaterialParams {
    // Fresnel
    pub fresnel_strength: f32,
    pub fresnel_power: f32,
    pub fresnel_color: [f32; 4],
    // Rim lighting
    pub rim_light: f32,
    pub rim_color: [f32; 4],
    pub rim_power: f32,
    // Distance fade
    pub distance_fade_start: Option<f32>,
    pub distance_fade_end: Option<f32>,
    // Screen-space effects
    pub dither: bool,
    pub pixel_snap: bool,
    pub outline: bool,
    pub outline_width: f32,
    pub outline_color: [f32; 4],
    // Animated effects
    pub scroll_speed: [f32; 2],
    pub rotation_speed: f32,
    pub pulsate: bool,
    pub pulsate_speed: f32,
    pub pulsate_min: f32,
    pub pulsate_max: f32,
}

impl Default for SpecialMaterialParams {
    fn default() -> Self {
        Self {
            fresnel_strength: 0.0, fresnel_power: 5.0, fresnel_color: [1.0, 1.0, 1.0, 1.0],
            rim_light: 0.0, rim_color: [1.0, 1.0, 1.0, 1.0], rim_power: 3.0,
            distance_fade_start: None, distance_fade_end: None,
            dither: false, pixel_snap: false, outline: false,
            outline_width: 2.0, outline_color: [0.0, 0.0, 0.0, 1.0],
            scroll_speed: [0.0, 0.0], rotation_speed: 0.0,
            pulsate: false, pulsate_speed: 1.0, pulsate_min: 0.0, pulsate_max: 1.0,
        }
    }
}

// ─── Tessellation ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TessellationSettings {
    pub mode: TessMode,
    pub factor: f32,         // 1.0 = no tessellation, 64.0 = max
    pub max_edge_length: f32,
    pub screen_space: bool,  // tessellate based on screen-space edge length
    pub displacement_strength: f32,
    pub lod_bias: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TessMode {
    Flat,           // no smoothing
    PnTriangles,    // smooth normals
    Phong,          // best quality
    Adaptive,       // distance-based
}

// ─── Wind Response ────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindMaterialResponse {
    pub mode: WindMode,
    pub strength: f32,
    pub frequency: f32,
    pub bend_height: f32,     // how high up bending starts (0 = root, 1 = tip)
    pub turbulence: f32,
    pub leaf_ripple: bool,    // secondary small motion for leaves
    pub leaf_ripple_strength: f32,
    pub stiffness: f32,       // how quickly it returns to rest
    pub wind_texture: Option<String>, // flow map for complex wind patterns
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WindMode {
    Simple,    // single direction sway
    Foliage,   // grass/shrub bending
    Tree,      // trunk + branch + leaf separation
    Cloth,     // connected to cloth simulation
    Palm,      // tropical palm tree movement
}

// ─── Material Presets ─────────────────────────────────────────────────────────

impl Material {
    pub fn default_standard(name: &str) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            name: name.to_string(),
            material_type: MaterialType::Standard,
            albedo: TextureRef::white(),
            albedo_tint: [1.0, 1.0, 1.0, 1.0],
            normal: TextureRef::flat_normal(),
            normal_strength: 1.0,
            normal_map_format: NormalMapFormat::OpenGl,
            roughness: TextureRef::None,
            roughness_value: 0.5,
            metallic: TextureRef::None,
            metallic_value: 0.0,
            ao: TextureRef::None,
            ao_strength: 1.0,
            emissive: TextureRef::None,
            emissive_color: [0.0, 0.0, 0.0],
            emissive_strength: 0.0,
            height: TextureRef::None,
            height_scale: 0.0,
            height_bias: 0.5,
            parallax_mode: ParallaxMode::None,
            opacity: TextureRef::None,
            opacity_value: 1.0,
            blend_mode: BlendMode::Opaque,
            alpha_cutoff: 0.5,
            alpha_dither: false,
            alpha_to_coverage: false,
            transmission: 0.0,
            transmission_color: [1.0, 1.0, 1.0],
            ior: 1.5,
            refraction_scale: 1.0,
            sss_enabled: false,
            sss_color: [1.0, 0.9, 0.8],
            sss_radius: [1.0, 0.5, 0.25],
            sss_profile: SssProfile::Skin,
            sss_anisotropy: 0.0,
            sss_strength: 1.0,
            clearcoat: 0.0,
            clearcoat_roughness: 0.0,
            clearcoat_normal: TextureRef::None,
            sheen: 0.0,
            sheen_roughness: 0.5,
            sheen_color: [1.0, 1.0, 1.0],
            iridescence: 0.0,
            iridescence_ior: 1.3,
            iridescence_thickness_min: 100.0,
            iridescence_thickness_max: 400.0,
            anisotropy: 0.0,
            anisotropy_rotation: 0.0,
            anisotropy_map: TextureRef::None,
            special: SpecialMaterialParams::default(),
            two_sided: false,
            cull_mode: CullMode::Back,
            depth_write: true,
            depth_test: true,
            depth_bias: 0.0,
            wireframe: false,
            cast_shadow: true,
            receive_shadow: true,
            receive_decals: true,
            receive_ao: true,
            vertex_color_multiplier: false,
            uv: UvSettings::default(),
            uv_channel_albedo: 0,
            uv_channel_normal: 0,
            uv_channel_roughness: 0,
            uv_channel_ao: 1, // AO usually on second UV channel
            tessellation: None,
            wind_response: None,
            tags: Vec::new(),
            custom_params: HashMap::new(),
            shader_graph_id: None,
        }
    }

    // ─── Material Presets ─────────────────────────────────────────────────

    pub fn chrome() -> Self {
        let mut m = Self::default_standard("Chrome");
        m.metallic_value = 1.0; m.roughness_value = 0.02;
        m.albedo_tint = [0.9, 0.9, 0.95, 1.0]; m
    }

    pub fn gold() -> Self {
        let mut m = Self::default_standard("Gold");
        m.metallic_value = 1.0; m.roughness_value = 0.1;
        m.albedo_tint = [1.0, 0.766, 0.336, 1.0]; m
    }

    pub fn rust() -> Self {
        let mut m = Self::default_standard("Rust");
        m.metallic_value = 0.2; m.roughness_value = 0.85;
        m.albedo = TextureRef::Procedural(ProceduralTexture {
            proc_type: ProceduralType::Rust { coverage: 0.6, edge_only: false },
            resolution: 512, scale: 2.0, offset: [0.0; 3],
            color_a: [0.4, 0.1, 0.0, 1.0], color_b: [0.6, 0.25, 0.1, 1.0], seed: 42,
        }); m
    }

    pub fn human_skin(skin_tone: [f32; 4]) -> Self {
        let mut m = Self::default_standard("Human Skin");
        m.material_type = MaterialType::Skin { skin_tone, subsurface_weight: 0.8 };
        m.sss_enabled = true;
        m.sss_profile = SssProfile::Skin;
        m.sss_color = [1.0, 0.4, 0.25];
        m.sss_radius = [1.0, 0.5, 0.25];
        m.roughness_value = 0.6;
        m.metallic_value = 0.0; m
    }

    pub fn glass(tint: [f32; 4]) -> Self {
        let mut m = Self::default_standard("Glass");
        m.material_type = MaterialType::Glass { tint, frosted: false, thickness: 0.002 };
        m.transmission = 0.95;
        m.ior = 1.52;
        m.roughness_value = 0.0;
        m.metallic_value = 0.0;
        m.blend_mode = BlendMode::AlphaBlend;
        m.opacity_value = 0.15;
        m.two_sided = true; m
    }

    pub fn water_surface() -> Self {
        let mut m = Self::default_standard("Water");
        m.material_type = MaterialType::Water { wave_normal: None, foam_texture: None,
            depth_color: [0.0, 0.2, 0.4, 1.0] };
        m.roughness_value = 0.05;
        m.metallic_value = 0.0;
        m.transmission = 0.8;
        m.ior = 1.33;
        m.blend_mode = BlendMode::AlphaBlend;
        m.opacity_value = 0.7;
        m.albedo_tint = [0.0, 0.3, 0.6, 1.0];
        m.two_sided = false; m
    }

    pub fn foliage(color: [f32; 4]) -> Self {
        let mut m = Self::default_standard("Foliage");
        m.material_type = MaterialType::Foliage { translucency: 0.3,
            subsurface_color: [0.2, 0.8, 0.1], wind_influence: 0.5 };
        m.albedo_tint = color;
        m.roughness_value = 0.8;
        m.two_sided = true;
        m.blend_mode = BlendMode::AlphaTest;
        m.alpha_cutoff = 0.3;
        m.wind_response = Some(WindMaterialResponse {
            mode: WindMode::Foliage, strength: 0.3, frequency: 1.2,
            bend_height: 0.2, turbulence: 0.4, leaf_ripple: true,
            leaf_ripple_strength: 0.15, stiffness: 0.8, wind_texture: None,
        }); m
    }

    pub fn velvet(color: [f32; 4]) -> Self {
        let mut m = Self::default_standard("Velvet");
        m.material_type = MaterialType::Fabric { fabric_type: FabricType::Velvet { backscatter: 0.6 } };
        m.albedo_tint = color;
        m.sheen = 1.0; m.sheen_roughness = 0.5;
        m.sheen_color = [color[0]*0.8, color[1]*0.8, color[2]*0.8];
        m.roughness_value = 0.9; m
    }

    pub fn hologram(color: [f32; 4]) -> Self {
        let mut m = Self::default_standard("Hologram");
        m.material_type = MaterialType::Hologram { scan_line_density: 40.0, edge_glow: 0.8, distortion: 0.05 };
        m.emissive_color = [color[0], color[1], color[2]];
        m.emissive_strength = 2.0;
        m.blend_mode = BlendMode::Additive;
        m.opacity_value = 0.6;
        m.two_sided = true;
        m.special.scroll_speed = [0.0, 0.1]; m
    }

    pub fn lava() -> Self {
        let mut m = Self::default_standard("Lava");
        m.material_type = MaterialType::Lava {
            flow_speed: 0.05,
            hot_color: [1.0, 0.9, 0.2, 1.0],
            cool_color: [0.1, 0.0, 0.0, 1.0],
        };
        m.emissive_strength = 3.0;
        m.roughness_value = 0.95; m
    }

    pub fn car_paint(color: [f32; 4]) -> Self {
        let mut m = Self::default_standard("Car Paint");
        m.albedo_tint = color;
        m.metallic_value = 0.0;
        m.roughness_value = 0.15;
        m.clearcoat = 1.0;
        m.clearcoat_roughness = 0.05; m
    }

    pub fn is_transparent(&self) -> bool {
        matches!(self.blend_mode, BlendMode::AlphaBlend | BlendMode::Additive | BlendMode::Premultiplied)
    }

    pub fn uses_sss(&self) -> bool {
        self.sss_enabled || matches!(self.material_type, MaterialType::Skin { .. })
    }
}

// ─── Material Library ─────────────────────────────────────────────────────────

pub struct MaterialLibrary {
    pub materials: HashMap<String, Material>,
    pub categories: HashMap<String, Vec<String>>,
    pub favorites: Vec<String>,
    pub recently_used: std::collections::VecDeque<String>,
}

impl MaterialLibrary {
    pub fn new() -> Self {
        let mut lib = Self {
            materials: HashMap::new(),
            categories: HashMap::new(),
            favorites: Vec::new(),
            recently_used: std::collections::VecDeque::new(),
        };
        lib.load_built_in_materials();
        lib
    }

    fn load_built_in_materials(&mut self) {
        let presets: Vec<(&str, &str, Material)> = vec![
            ("Default White", "Basic", Material::default_standard("Default White")),
            ("Chrome",  "Metal",  Material::chrome()),
            ("Gold",    "Metal",  Material::gold()),
            ("Rust",    "Metal",  Material::rust()),
            ("Human Skin", "Organic", Material::human_skin([0.85, 0.65, 0.5, 1.0])),
            ("Glass Clear", "Glass",  Material::glass([1.0, 1.0, 1.0, 1.0])),
            ("Glass Green", "Glass",  Material::glass([0.8, 1.0, 0.8, 1.0])),
            ("Water Surface", "Liquid", Material::water_surface()),
            ("Grass", "Foliage", Material::foliage([0.2, 0.7, 0.1, 1.0])),
            ("Bush", "Foliage", Material::foliage([0.15, 0.5, 0.1, 1.0])),
            ("Velvet Red", "Fabric",  Material::velvet([0.7, 0.1, 0.1, 1.0])),
            ("Velvet Blue", "Fabric", Material::velvet([0.1, 0.2, 0.8, 1.0])),
            ("Hologram Cyan", "Special", Material::hologram([0.0, 1.0, 1.0, 1.0])),
            ("Lava", "Special", Material::lava()),
            ("Car Paint Red", "Vehicles", Material::car_paint([0.8, 0.1, 0.1, 1.0])),
        ];

        for (name, cat, mat) in presets {
            let id = mat.id.clone();
            self.categories.entry(cat.to_string()).or_default().push(id.clone());
            self.materials.insert(id, mat);
        }
    }

    pub fn get(&self, id: &str) -> Option<&Material> { self.materials.get(id) }
    pub fn get_mut(&mut self, id: &str) -> Option<&mut Material> { self.materials.get_mut(id) }

    pub fn add(&mut self, material: Material) -> String {
        let id = material.id.clone();
        self.materials.insert(id.clone(), material);
        self.recently_used.push_front(id.clone());
        if self.recently_used.len() > 20 { self.recently_used.pop_back(); }
        id
    }

    pub fn search(&self, query: &str) -> Vec<&Material> {
        let q = query.to_lowercase();
        self.materials.values()
            .filter(|m| m.name.to_lowercase().contains(&q) || m.tags.iter().any(|t| t.to_lowercase().contains(&q)))
            .collect()
    }

    pub fn by_category(&self, category: &str) -> Vec<&Material> {
        self.categories.get(category)
            .map(|ids| ids.iter().filter_map(|id| self.materials.get(id)).collect())
            .unwrap_or_default()
    }

    pub fn count(&self) -> usize { self.materials.len() }
}

extern crate uuid;
pub mod graph;
