[package]
name = "genesis-export"
version = { workspace = true }
edition.workspace = true
[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
async-trait.workspace = true
uuid = { workspace = true }
genesis-core = { workspace = true }
genesis-math = { workspace = true }
